version: '3'
services:
  master:
    image: redis:5.0-alpine
    networks:
      - services

  slave:
    image: redis:5.0-alpine
    command: redis-server --slaveof master 6379
    networks:
      - services

  sentinel:
    image: redis:5.0-alpine
    command: >
      sh -c "
        echo 'port 26379' > sentinel.conf &&
        echo 'dir /tmp' >> sentinel.conf &&
        echo 'sentinel monitor master master 6379 2' >> sentinel.conf &&
        echo 'sentinel down-after-milliseconds master 5000' >> sentinel.conf &&
        echo 'sentinel parallel-syncs master 1' >> sentinel.conf &&
        echo 'sentinel failover-timeout master 5000' >> sentinel.conf &&
      cat sentinel.conf &&
      redis-server sentinel.conf --sentinel"
    networks:
      - services

networks:
  services: