version: '3.6'

x-redis-base: &redis-base
  image: redis:5.0-alpine
  networks:
    - redis

services:
  master:
    <<: *redis-base
  
  slave:
    <<: *redis-base
    command: redis-server --slaveof master 6379

  sentinel:
    <<: *redis-base
    command:
      - /bin/sh 
      - -c
      - |
          tee sentinel.conf > /dev/null << EOF
            port 26379
            dir /tmp
            sentinel monitor master master 6379 2
            sentinel down-after-milliseconds master 5000
            sentinel parallel-syncs master 1
            sentinel failover-timeout master 5000
          EOF
          
          redis-server sentinel.conf --sentinel

networks:
  redis:
